### ISSUE TITLE
Unit testing with 'eoc'

### ISSUE THREAD

**Issue by includealex** [objectionary/eoc#31] opened 2022-08-10 09:34 UTC
As mentioned in [this](https://news.eolang.org/2022-06-19-eoc-test.html) article, user can easily start unit testing of eo-programs. But if user creates a program named `app.eo` in random directory with such a code
```
[] > name
  "Potted cactus" > @
[args...] > app
  QQ.io.stdout > @
    name

```
and then puts a unit-test into the `app-test.eo`  file to the same directory,  
```
+junit
+alias name
+alias org.eolang.hamcrest.assert-that

[] > the-name-is-right
  assert-that > @
    name.length
      $.lt 100

```
he will get an error after running `eoc test`.

**Comment by yegor256** [comment] 2023-01-15 07:08
@includealex this is a duplicate of https://github.com/objectionary/eo/issues/1323

**Closed by yegor256** 2023-01-15 07:08 UTC
