### ISSUE TITLE
Not full Error Stackstrace 

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eoc#57] opened 2022-09-08 14:12 UTC
```
Error at "EOorg.EOeolang.EObool#plus" attribute
Can't get(), attribute "plus" is absent among other 11 attrs (ρ, not, σ, or, Δ, and, as-bytes, eq, while, if, as-hash) and φ is absent
```

**Comment by MikhailLipanin** [comment] 2022-09-08 14:13
@yegor256

**Comment by yegor256** [comment] 2022-09-10 04:09
@mximp can you try to fix this? The problem is that we print a short list of error messages. For example, it doesn't include the line about the location of the object (line + pos). Probably the bug is in the `org.eolang.Main` class.

**Comment by mximp** [comment] 2022-09-29 10:40
@MikhailLipanin please advise on the above

**Comment by MikhailLipanin** [comment] 2022-09-30 14:49
@mxip it was a case, when I gave to object `plus.` attributes `BOOL` and `INT`, so for this example:
```
[] > app
  plus. > @
    TRUE
    228
```
Log is:
```
$ eoc clean && eoc dataize app
The directory /home/mlipanin/test2/.eoc deleted
EO version is 0.28.7
EO objects registered in /home/mlipanin/test2/.eoc/eo-foreign.json
EO version is 0.28.7
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.11.1
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.11.1
EO program assembled in /home/mlipanin/test2/.eoc
EO version is 0.28.7
Java sources generated in /home/mlipanin/test2/.eoc/generated-sources
EO version is 0.28.7
Java .class files compiled into /home/mlipanin/test2/.eoc
EO version is 0.28.7
Executable JAR created at /home/mlipanin/test2/.eoc/eoc.jar
The object is at the line #3, position #4
Error at "EOorg.EOeolang.EObool#plus" attribute
Can't get(), attribute "plus" is absent among other 11 attrs (ρ, not, σ, or, Δ, and, as-bytes, eq, while, if, as-hash) and φ is absent
```

**Comment by mximp** [comment] 2022-10-05 10:48
@MikhailLipanin @yegor256 
I believe the last 3 lines in the above log clearly state line/position and the issue.
What is wrong with that?

**Comment by mximp** [comment] 2022-10-05 10:51
Maybe it's worth to reformat the error message:
```
Exception occurred:
  The object is at the line #3, position #4, caused by
    Error at "EOorg.EOeolang.EObool#plus" attribute, caused by
      Can't get(), attribute "plus" is absent among other 11 attrs (ρ, not, σ, or, Δ, and, as-bytes, eq, while, if, as-hash) and φ is absent
```
What do you think?

**Comment by mximp** [comment] 2022-10-07 10:24
@yegor256 @MikhailLipanin So what are we doing with this? I think we can close it as I see nothing to fix/implement here.

**Comment by MikhailLipanin** [comment] 2022-10-07 10:50
@mximp as for me, this one:
```
Exception occurred:
  The object is at the line #3, position #4, caused by
    Error at "EOorg.EOeolang.EObool#plus" attribute, caused by
      Can't get(), attribute "plus" is absent among other 11 attrs (ρ, not, σ, or, Δ, and, as-bytes, eq, while, if, as-hash) and φ is absent
```
looks more understandable, @yegor256 What do you think?

**Comment by mximp** [comment] 2022-10-07 11:12
@MikhailLipanin I checked the code and it's not that easy to make the output look this way.
Is it really worth it?

**Comment by MikhailLipanin** [comment] 2022-10-07 13:39
@mximp I don't know, probably not...

**Comment by mximp** [comment] 2022-10-10 12:08
@MikhailLipanin let's close the issue then

**Closed** 2022-10-11 13:28 UTC
Labels: bug
